import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Faisal",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Astha",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: "Slim shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "/images/p1.jpg", // 640x444
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      // _id: '1',
      name: "Summer shirt",
      slug: "summer-shirt",
      category: "Shirts",
      image: "/images/p2.jpg", // 679px × 829px
      price: 120,
      countInStock: 7,
      brand: "Nike",
      rating: 4.8,
      numReviews: 8,
      description: "high quality shirt",
    },
    {
      // _id: '1',
      name: "T-shirt",
      slug: "t-shirt",
      category: "Shirts",
      image: "/images/p3.jpg", // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 5,
      numReviews: 8,
      description: "high quality shirt",
    },

    {
      // _id: '2',
      name: "Fit Shirt",
      slug: "fit-shirt",
      category: "Shirts",
      image: "/images/p4.jpg",
      price: 250,
      countInStock: 0,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      // _id: '2',
      name: "Girls T-Shirt",
      slug: "girls-t-shirt",
      category: "Shirts",
      image: "/images/p5.jpg",
      price: 250,
      countInStock: 0,
      brand: "Adidas",
      rating: 4.7,
      numReviews: 10,
      description: "high quality product",
    },
    {
      // _id: '3',
      name: "Slim Pant",
      slug: "nike-slim-pant",
      category: "Pants",
      image: "/images/p7.jpg",
      price: 25,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      // _id: '4',
      name: "Fit Pant",
      slug: "adidas-fit-pant",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};
export default data;
